include .make_scripts/mkdocs-documentation/mkdocs-documentation-makefile.mk
# This includes make: doc-serve, doc-build, doc-build-docker, doc-run-docker, doc-create-mkdocs, doc-setup, doc-site-clean, doc-fix-symlinks and doc-update-assets.
# NOTE: mkdocs.yml is AUTOGENERATED from mkdocs_custom.yml + the shared mkdocs_base.yml — never edit it by hand.
include .make_scripts/project-infrastructure/project-infrastructure-makefile
# This includes make: sync-infrastructure-assets, github-autodelete-merged-branches, github-set-branch-protections and github-set-default-branch
include .make_scripts/release-management/release-management-makefile
# This includes make: tag-major, tag-major-beta, tag-minor, tag-minor-beta, tag-patch, tag-patch-beta, tag-latest-beta, tag-major-minor-ruleset, hard-reset-tags, check-for-releases and sync-release-assets.

# containerlab launcher: runs ghcr.io/srl-labs/clab through the docker socket,
# the same on Linux and macOS (see the header of ./containerlab).
CONTAINERLAB ?= ./containerlab

# Which lab this checkout runs. `make scenarios` lists them; everything a
# scenario can own lives under scenarios/<name>/, overlaid on scenarios/_base/.
# This is the ONLY default: every script, compose file and bash entry point
# reads SCENARIO and fails when it is unset, so a scenario is never half-applied.
SCENARIO ?= wan-and-fabric
export SCENARIO
# The scenario's source assets, its resolved overlay, and the artifacts the
# generators write beside it.
SCENARIO_SRC := scenarios/$(SCENARIO)
SCENARIO_DIR := generated/$(SCENARIO)/scenario
GEN_DIR := generated/$(SCENARIO)

# Wait budgets (seconds). Defaults suit a native Linux host; a Mac booting the
# SR Linux nodes against a shared VM raises these rather than removing a wait.
WAIT_READY_TIMEOUT ?= 180
WAIT_DEVICES_TIMEOUT ?= 240

# Kubernetes flavour of the lab (`make kind-lab-*`): the cluster to load the FRR
# image into, and the namespace the device pods live in. The cluster is shared
# with other projects — these targets only ever touch $(KIND_LAB_NAMESPACE).
KIND_CLUSTER ?= kind
KIND_LAB_NAMESPACE ?= neops-lab
KIND_LAB_TIMEOUT ?= 180
KIND_MANIFEST := $(GEN_DIR)/kind/lab.yaml

# The NeOps product stack `make kind-lab-cms-config` configures. It is a
# separate deployment in its own namespace; nothing here installs, changes or
# deletes it beyond the `neops` user's role and the Global scope.
NEOPS_NAMESPACE ?= neops
NEOPS_CMS_DEPLOYMENT ?= neops-neops-core
# The workflow engine is issued a CMS API key at install; the lab borrows it
# rather than minting a second one.
NEOPS_CMS_TOKEN_SECRET ?= neops-neops-workflow-engine
NEOPS_CMS_SERVICE ?= neops-neops-core
NEOPS_CMS_PORT ?= 8000
# The host talks to the CMS through a short-lived `kubectl port-forward`, not
# through its ingress: no public DNS, no TLS and no ingress controller needed,
# and it works on any cluster this kubectl can reach.
CMS_PORT ?= 18000
CMS_URL ?= http://127.0.0.1:$(CMS_PORT)
# How apply_cms_config runs `manage.py` inside that CMS. Its own default is the
# compose lab, so the Kubernetes flavour supplies the kubectl form here.
CMS_EXEC ?= kubectl -n $(NEOPS_NAMESPACE) exec -i deploy/$(NEOPS_CMS_DEPLOYMENT) --

# Extra flags for every docker build, e.g. DOCKER_BUILD_FLAGS=--network=host when the bridge network has no DNS.
DOCKER_BUILD_FLAGS ?=
# -----------------------------------------------------------------------------
# Images built from this repo. Local tags only — nothing here is published to a
# registry; the lab always builds its two helper images on the machine that runs
# it. (The worker, CMS, engine and web client all come from quay.io.)
# -----------------------------------------------------------------------------
build-docker: build-docker-frr build-docker-bootstrap

# Custom FRR image (frrouting/frr + sshd + frr/frr login) that containerlab runs
# as `kind: linux` and that the Kubernetes lab runs as a pod.
build-docker-frr:
	docker build $(DOCKER_BUILD_FLAGS) -t neops-lab-frr:latest devices/frr

# One-shot container that POSTs the scenario's workflows/*.yaml to the engine.
build-docker-bootstrap:
	docker build $(DOCKER_BUILD_FLAGS) -t neops-lab-bootstrap:latest bootstrap

lint:
	uv run ruff format --check .
	uv run ruff check .

format:
	uv run ruff format .
	uv run ruff check --fix .

typeCheck:
	uv run pyrefly check

test:
	uv run pytest tests

# The host scripts must import under Python 3.9, the python3 a stock macOS
# ships; ruff at `target-version py312` accepts syntax that breaks there.
py39-check:
	uv run --python 3.9 --no-project python tools/import_host_scripts.py

# Syntax gate for the bash entry points (macOS ships bash 3.2).
shell-syntax:
	bash -n apply_cms_config
	bash -n containerlab
	bash -n doctor

# Host preflight; read-only apart from pulling busybox / the clab image.
doctor:
	@./doctor

check: lint typeCheck test py39-check shell-syntax

# Dev-only RSA keypair for the CMS. Newer neops-cms-free images require it for
# RS256 JWT issuance and crash at startup (token_service check_keys) without it,
# and docker-compose.yml mounts cms/jwt into the container — so a fresh clone
# cannot start the stack until this has run once. Idempotent: an existing
# keypair is left alone, so re-running never invalidates issued tokens.
# The keys are git-ignored; they are throwaway lab credentials, never secrets.
# `genpkey` rather than `genrsa`: OpenSSL 3 and the LibreSSL a stock macOS
# ships then emit the same PKCS#8 PEM.
lab-jwt:
	@mkdir -p cms/jwt
	@if [ -f cms/jwt/private.pem ] && [ -f cms/jwt/public.pem ]; then \
		echo "cms/jwt keypair already present — skipping"; \
	else \
		openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out cms/jwt/private.pem && \
		openssl rsa -in cms/jwt/private.pem -pubout -out cms/jwt/public.pem && \
		echo "generated cms/jwt/{private,public}.pem"; \
	fi

# A fresh clone has no .env; copy the example so there is one to edit (every
# value in it is commented out, so this changes no behaviour on its own).
lab-env:
	@if [ -f .env ]; then \
		echo ".env already present — skipping"; \
	else \
		cp .env.example .env && echo "created .env from .env.example"; \
	fi

local-env-init: lab-jwt scenario-resolve
	touch cms_api_key.env
	# Refresh the published images. `--ignore-pull-failures` is load-bearing: if
	# you override a service with a locally-built tag
	# (NEOPS_*_IMAGE=neops-workflow-engine:latest), docker resolves it as
	# docker.io/library/... and the pull fails with "repository does not exist",
	# which would abort the whole target. With the flag the published images
	# still refresh and the local one is merely warned about.
	# `--policy always` overrides the services' `pull_policy: missing`, which
	# `docker compose pull` also honours and which would skip any image already
	# on disk.
	# `docker compose up -d` needs no such care — the compose files set
	# `pull_policy: missing`, so a local image already present is used as-is.
	docker compose pull --policy always --ignore-pull-failures
	docker compose up -d
	# Mint the engine's CMS API key for the `neops` user, resolving the pk by
	# name (a re-init over a preserved volume can hold a different pk).
	# generate_api_key prints the key on the last non-empty line (current CMS
	# images print no `api key:` label); an empty key fails here.
	@pk=$$(docker compose exec -T cms ./manage.py shell -c "from django.contrib.auth import get_user_model; print('PK=%s' % get_user_model().objects.get(username='neops').pk)" 2>/dev/null | sed -n 's/^PK=//p' | tr -d '\r'); \
	test -n "$$pk" || { echo "error: could not resolve the CMS user 'neops'"; exit 1; }; \
	key=$$(docker compose exec -T cms ./manage.py generate_api_key $$pk workflow 2>/dev/null | awk 'NF{l=$$0}END{print l}' | tr -d '\r'); \
	test -n "$$key" || { echo "error: generate_api_key returned an empty key"; exit 1; }; \
	echo "NEOPS_CMS_TOKEN=$$key" > cms_api_key.env; \
	echo "wrote cms_api_key.env (user pk $$pk)"
	# Apply CMS config (grants the neops user access to the Global scope) BEFORE
	# recreating the engine. The CMS caches each user's accessible scopes
	# in-memory for 10 min; if the engine queries the CMS as neops before the
	# grant, that stale (empty) cache hides the Global scope from the web client
	# for up to 10 min ("scope not available when first used"). Granting first
	# means the first neops query caches the grant.
	./apply_cms_config
	# env_file changes don't trigger recreate on their own; force it so the engine picks up the new token
	docker compose up -d --force-recreate workflow_engine

local-env-up: lab-jwt scenario-resolve
	@if [ ! -f cms_api_key.env ]; then echo "Error: cms_api_key.env file not found. Please run 'make local-env-init' first."; exit 1; fi
	# See the note in local-env-init about --policy always / --ignore-pull-failures.
	docker compose pull --policy always --ignore-pull-failures
	docker compose up -d

local-env-down:
	# Stops the base stack but KEEPS the volumes, so CMS data survives.
	docker compose down

local-env-prune:
	# `-v` removes the elasticsearch + postgres_data volumes too — leftover
	# state across down/up cycles caused `elastic_index --create` to fail
	# and stale CMS data to confuse re-inits.
	docker compose down -v

# -----------------------------------------------------------------------------
# Scenarios — see docs/30-scenarios/
# -----------------------------------------------------------------------------

scenarios:
	@./resolve_scenario --list

# Materialise scenarios/_base + scenarios/$(SCENARIO) into $(SCENARIO_DIR), the
# one flat directory the containers mount and the scripts read. docker compose
# cannot express a fallback in a bind mount, so the overlay is resolved here
# instead. Cheap enough to be a prerequisite of every scenario-consuming target,
# which is what makes a stale overlay impossible.
scenario-resolve:
	@./resolve_scenario --quiet

# Regenerate everything derived from the scenario's topology, including the
# committed workflow-execution-parameters/*.json. Commit those: `make test`
# asserts they reproduce byte-for-byte.
generate: scenario-resolve
	@./gen_clab_topology

# -----------------------------------------------------------------------------
# Simple Lab — see README.md
# -----------------------------------------------------------------------------

# Lab targets run the base stack plus the per-vendor device files and the worker
# overlay, selected via docker compose's COMPOSE_FILE env variable (colon-
# separated). The export is scoped to the lab targets so `local-env-*` keep
# using the base docker-compose.yml only.
LAB_COMPOSE_FILES := docker-compose.yml:docker-compose.worker.yml
local-lab-up local-lab-down local-lab-discover local-lab-logs: export COMPOSE_FILE := $(LAB_COMPOSE_FILES)
local-lab-up local-lab-down local-lab-discover local-lab-logs: export COMPOSE_PATH_SEPARATOR := :

# Function block the discovery workflow dispatches to. The worker registers it
# with the engine asynchronously after startup; `wait_ready` blocks on that.
DISCOVER_FB := fb.base.neops.io/global_discover_network:0.1.0

# Execution parameters for the discovery workflow. Override to discover with a
# different target form, e.g.
#   make local-lab-discover DISCOVER_PARAMS=$(SCENARIO_SRC)/workflow-execution-parameters/discover-params-autodetect.json
#   make local-lab-discover DISCOVER_PARAMS=$(SCENARIO_SRC)/workflow-execution-parameters/discover-params-subnet.json
#   make local-lab-discover DISCOVER_PARAMS=$(SCENARIO_SRC)/workflow-execution-parameters/discover-params-mixed.json
DISCOVER_PARAMS ?= $(SCENARIO_SRC)/workflow-execution-parameters/discover-params.json

# containerlab topology (generated from the scenario's topology.json).
CLAB_TOPO := $(GEN_DIR)/clab/neops-lab.clab.json

# containerlab needs root to create netns/veths. Rather than sudo-ing every lab
# target (which would prompt for a password in the middle of `local-lab-up`),
# containerlab's supported model is a SUID binary plus membership in the
# `clab_admins` group — see Prerequisites in README.md.
# Run this once after installing containerlab, and again after **upgrading** it:
# a package upgrade replaces the binary and silently drops the SUID bit, which
# resurfaces as `local-lab-up` failing with "This containerlab command requires
# root privileges or root via SUID to run, effective UID: 1000 SUID: 1000".
# Deliberately NOT a prerequisite of local-lab-up: it is the one target that
# needs sudo, so it stays opt-in. Idempotent — an already-SUID binary is left
# alone, so re-running costs nothing (and skips the password prompt entirely).
clab-suid:
	@CLAB=$$(command -v containerlab) || { echo "Error: containerlab not found in PATH."; exit 1; }; \
	if [ -u "$$CLAB" ]; then \
		echo "SUID bit already set on $$CLAB — skipping"; \
	else \
		echo "Setting SUID bit on $$CLAB (needs sudo)..."; \
		sudo chmod u+s "$$CLAB" || exit 1; \
		echo "done: $$(ls -l "$$CLAB")"; \
	fi; \
	if ! id -nG | tr ' ' '\n' | grep -qx clab_admins; then \
		echo "Warning: $$USER is not in the clab_admins group — privileged containerlab"; \
		echo "         commands will still be refused. Fix with:"; \
		echo "           sudo groupadd -r clab_admins && sudo usermod -aG clab_admins $$USER"; \
		echo "         then re-login for the group to apply."; \
	fi

local-lab-up: build-docker lab-env scenario-resolve
	@if [ ! -f cms_api_key.env ]; then echo "Error: run 'make local-env-init' first."; exit 1; fi
	# Generate the containerlab topology + per-device configs from the scenario.
	@./gen_clab_topology
	# Refresh the worker image: the local-env-* pulls run with the base compose
	# file, which does not include the worker service.
	docker compose pull --policy always --ignore-pull-failures worker
	# Base stack + worker + bootstrap. This creates the `lab-net` network that
	# containerlab attaches the devices to, and registers the workflow definitions.
	# `up -d` returns once containers are *Started*, not *Completed*; the one-shot
	# `lab_bootstrap` container registers the workflow definitions (e.g.
	# simple_lab_discovery) with the engine and then exits.
	docker compose up -d
	# Without this wait, `local-lab-discover` races ahead and the engine 404s with
	# "Workflow with ID null not found". `wait` blocks until it exits and
	# propagates its exit code, so a failed registration fails this target.
	@echo "Waiting for workflow registration (lab_bootstrap) to finish..."
	docker compose wait lab_bootstrap
	# Deploy the 15 devices with REAL point-to-point wiring onto lab-net. SR Linux
	# boots slowly, so deploy early — before waiting on device SSH below.
	@echo "Deploying containerlab devices (real links)..."
	$(CONTAINERLAB) deploy --reconfigure -t $(CLAB_TOPO)
	# The worker registers its function blocks with the engine asynchronously
	# after its container starts. Block until an online worker exists so the
	# "Lab is up" banner is honest and `local-lab-discover` won't race the
	# worker with "Function block ... not found".
	@echo "Waiting for the worker to register its function blocks..."
	@./wait_ready --timeout $(WAIT_READY_TIMEOUT) $(DISCOVER_FB) || { echo; docker compose ps worker; echo "(worker log tail:)"; docker compose logs --no-log-prefix --tail 15 worker; exit 1; }
	# Devices (esp. Nokia SR Linux) boot slower than `containerlab deploy` returns.
	# Poll from *inside* the lab network (the worker is on lab-net), not the host.
	# On macOS/Docker Desktop the host has no route to the lab-net bridge IPs
	# (172.30.0.0/24), so a host-side poll hangs until timeout even though the
	# devices are healthy. Container-to-container reachability — the same path
	# discovery actually uses — works on every platform.
	# The repo is mounted at /app/lab in the worker, hence the `lab/` prefix here.
	@echo "Waiting for all devices to accept SSH..."
	@docker compose exec -T -e SCENARIO=$(SCENARIO) worker python3 lab/wait_devices --timeout $(WAIT_DEVICES_TIMEOUT)
	@echo ""
	@echo "Lab is up (scenario: $(SCENARIO), real links)."
	@echo "  Web client:   http://localhost:8080/"
	@echo "  Engine UI:    http://localhost:3031"
	@echo "  Engine API:   http://localhost:3030/"
	@echo "  CMS admin:    http://localhost:8001/admin/ (neops / neops)"
	@echo "  CMS GraphQL:  http://localhost:8001/graphql"
	@echo "  Run 'make local-lab-discover' to populate the CMS (15 devices with interfaces)."

local-lab-down:
	# --cleanup removes the per-lab runtime dir
	# (generated/<scenario>/clab/clab-neops-lab); the leading `-` lets `make`
	# continue if no lab is deployed.
	-$(CONTAINERLAB) destroy -t $(CLAB_TOPO) --cleanup
	docker compose down

local-lab-discover: scenario-resolve
	@./wait_ready --timeout $(WAIT_READY_TIMEOUT) $(DISCOVER_FB)
	# Always wait for the known lab devices, not the requested discovery input:
	# a subnet target also contains unused addresses which must not block readiness.
	@docker compose exec -T -e SCENARIO=$(SCENARIO) worker python3 lab/wait_devices --timeout $(WAIT_DEVICES_TIMEOUT)
	# 15-minute timeout: discovering 15 devices (SSH + fact/interface collection
	# across 10 FRR + 5 slower Nokia SR Linux nodes) legitimately exceeds the
	# run_workflow 300s default. Autodetection adds an SSH probe per host, so the
	# same ceiling covers both parameter files.
	@./run_workflow --timeout 900 wf.lab.neops.io/simple_lab_discovery:1.2.0 @$(DISCOVER_PARAMS)

apply-cms-config: scenario-resolve
	./apply_cms_config

local-lab-logs:
	docker compose logs -f worker lab_bootstrap

# -----------------------------------------------------------------------------
# Kubernetes Lab — the FRR devices as pods in a local KIND cluster.
#
# Standalone: no containerlab, no docker-compose, no local-env-* stack. Only the
# 10 FRR devices are rendered; the 5 SR Linux nodes are far too heavy for a
# shared local cluster (see gen_kind_manifests). Devices carry no mgmt IP here —
# they are reached by in-cluster DNS, `<device>.$(KIND_LAB_NAMESPACE).svc.cluster.local`.
# -----------------------------------------------------------------------------

kind-lab-up: build-docker-frr scenario-resolve
	# The cluster has no registry, so the image is pushed straight onto the
	# nodes; that is what makes the manifests' `imagePullPolicy: IfNotPresent`
	# resolve without a pull.
	kind load docker-image neops-lab-frr:latest --name $(KIND_CLUSTER)
	@./gen_kind_manifests --namespace $(KIND_LAB_NAMESPACE)
	kubectl apply -f $(KIND_MANIFEST)
	# Not `wait_devices`, which is the containerlab flavour's TCP-22 poll: its
	# check already runs here as each pod's `tcpSocket: 22` readinessProbe, from
	# inside the cluster where the addresses actually resolve. A host-side poll
	# cannot reach a ClusterIP or a *.svc.cluster.local name at all.
	@echo "Waiting for the device pods to become ready..."
	kubectl -n $(KIND_LAB_NAMESPACE) wait --for=condition=Available --timeout=$(KIND_LAB_TIMEOUT)s deployment --all
	@echo ""
	@echo "Kubernetes lab is up in namespace $(KIND_LAB_NAMESPACE) (scenario: $(SCENARIO), FRR devices only, login frr / frr)."
	@kubectl -n $(KIND_LAB_NAMESPACE) get svc -o jsonpath='{range .items[*]}  {.metadata.name}.{.metadata.namespace}.svc.cluster.local{"\n"}{end}'
	@echo ""
	@echo "  Run 'make kind-lab-status' for pods and services."

kind-lab-down:
	# Deleting the namespace takes every device with it and touches nothing else
	# in this shared cluster.
	kubectl delete namespace $(KIND_LAB_NAMESPACE) --ignore-not-found

kind-lab-status:
	@kubectl -n $(KIND_LAB_NAMESPACE) get pods,svc

# Applying the CMS config is deliberately a SEPARATE target: bringing the pods up
# must not require a running product stack, the same way local-lab-up and
# local-lab-discover are separate today.
#
# `apply_cms_config` is the compose lab's own script, reused through CMS_EXEC
# rather than forked: it grants the `neops` user the `lab-admin` role and seeds
# the Global scope, without which the web client shows no scope at all. Getting
# the devices themselves into the CMS is discovery's job, not a second
# implementation of it here — see the Kubernetes lab docs.
#
# The API key is read out of the cluster Secret per invocation, so it is never
# stale, and the recipe is `@`-prefixed so it is never echoed.
kind-lab-cms-config: scenario-resolve
	@kubectl -n $(NEOPS_NAMESPACE) port-forward svc/$(NEOPS_CMS_SERVICE) $(CMS_PORT):$(NEOPS_CMS_PORT) >/dev/null & \
	pf=$$!; trap 'kill $$pf 2>/dev/null || true' EXIT; \
	i=0; until curl -s -o /dev/null --max-time 2 $(CMS_URL)/; do \
		i=$$((i + 1)); test $$i -lt 30 || { echo "error: port-forward to $(NEOPS_CMS_SERVICE) never came up" >&2; exit 1; }; \
		sleep 1; \
	done; \
	CMS_URL="$(CMS_URL)" CMS_EXEC="$(CMS_EXEC)" \
	NEOPS_CMS_TOKEN="$$(kubectl -n $(NEOPS_NAMESPACE) get secret $(NEOPS_CMS_TOKEN_SECRET) -o jsonpath='{.data.NEOPS_CMS_TOKEN}' | base64 -d)" \
	./apply_cms_config

.PHONY: build-docker build-docker-frr build-docker-bootstrap doctor lint format typeCheck test py39-check \
	shell-syntax check lab-jwt lab-env clab-suid \
	scenarios scenario-resolve generate \
	local-env-init local-env-up local-env-down local-env-prune \
	local-lab-up local-lab-down local-lab-discover local-lab-logs apply-cms-config \
	kind-lab-up kind-lab-down kind-lab-status kind-lab-cms-config
