# Like dynamic.https.yml but routers use the letsencrypt certResolver.

http:
  middlewares:
    engine-strip:
      stripPrefix:
        prefixes:
          - /engine
    dashboard-strip:
      stripPrefix:
        prefixes:
          - /traefik

  routers:
    dashboard:
      rule: PathPrefix(`/traefik`)
      entryPoints:
        - websecure
      priority: 200
      middlewares:
        - dashboard-strip
      service: api@internal
      tls:
        certResolver: letsencrypt

    cms:
      rule: PathPrefix(`/cms`)
      entryPoints:
        - websecure
      priority: 100
      service: cms
      tls:
        certResolver: letsencrypt

    engine:
      rule: PathPrefix(`/engine`)
      entryPoints:
        - websecure
      priority: 100
      middlewares:
        - engine-strip
      service: engine
      tls:
        certResolver: letsencrypt

    monitor:
      rule: PathPrefix(`/monitor`)
      entryPoints:
        - websecure
      priority: 100
      service: monitor
      tls:
        certResolver: letsencrypt

    web:
      rule: PathPrefix(`/`)
      entryPoints:
        - websecure
      priority: 1
      service: web
      tls:
        certResolver: letsencrypt

  services:
    cms:
      loadBalancer:
        servers:
          - url: http://cms-proxy:80
    engine:
      loadBalancer:
        servers:
          - url: http://workflow_engine:3030
    monitor:
      loadBalancer:
        servers:
          - url: http://workflow-engine-client:5173
    web:
      loadBalancer:
        servers:
          - url: http://web_client:8080
